apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pz-server
    metallb.universe.tf/address-pool: fixed
  name: pz-nfs-tcp
  namespace: default
spec:
  ports:
  - name: tcp2049
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: tcp111
    port: 111
    protocol: TCP
    targetPort: 111
  - name: tcp32765
    port: 32765
    protocol: TCP
    targetPort: 32765
  - name: tcp32767
    port: 32767
    protocol: TCP
    targetPort: 32767
  selector:
    app: pz-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.112
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pz-server
    metallb.universe.tf/address-pool: fixed
  name: pz-nfs-udp
  namespace: default
spec:
  ports:
  - name: udp2049
    port: 2049
    protocol: UDP
    targetPort: 2049
  - name: udp111
    port: 111
    protocol: UDP
    targetPort: 111
  - name: udp32765
    port: 32765
    protocol: UDP
    targetPort: 32765
  - name: udp32767
    port: 32767
    protocol: UDP
    targetPort: 32767
  selector:
    app: pz-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.112