apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pz-server
  name: pz-server
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pz-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pz-server
    spec:
      initContainers:
        - name: file-permisions
          image: busybox:1.31.1
          command:
            - "/bin/sh"
            - "-c"
          args:
            - echo starting;
              echo "Chown server-data start";
              chown -R 1000:1000 server-data/ && echo "Chown server-data done";
              echo "Chown server-files start";
              chown -R 1000:1000 server-files/ && echo "Chown server-files done";
              echo "Chmod server-data start";
              chmod -R o+rwx server-data/ && echo "Chmod server-data done";
              echo done;
          volumeMounts:
            - mountPath: /server-data
              name: vol0
              subPath: ServerData
            - mountPath: /server-files
              name: vol0
              subPath: ServerFiles
      containers:
        - name: pz-server
          env:
            - name: SERVER_NAME
              value: "Ry963"
            - name: SERVER_PASSWORD
              value: "Pen15"
            - name: SERVER_PUBLIC_NAME
              value: "Ry963"
            - name: SERVER_PUBLIC_DESC
              value: "Hello"
            - name: SERVER_PORT 
              value: "16261"
            - name: ADMIN_PASSWORD
              value: "Pen155"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: afey/zomboid
          imagePullPolicy: Always
          ports:
            - containerPort: 8766
              name: 8766udp
              protocol: UDP
            - containerPort: 8767
              name: 8767udp
              protocol: UDP
            - containerPort: 16261
              name: 16261udp
              protocol: UDP
            - containerPort: 16262
              name: 16262tcp
              protocol: TCP
            - containerPort: 16263
              name: 16263tcp
              protocol: TCP
            - containerPort: 16264
              name: 16264tcp
              protocol: TCP
            - containerPort: 16265
              name: 16265tcp
              protocol: TCP
            - containerPort: 16266
              name: 16266tcp
              protocol: TCP
            - containerPort: 16267
              name: 16267tcp
              protocol: TCP
            - containerPort: 16268
              name: 16268tcp
              protocol: TCP
            - containerPort: 16269
              name: 16269tcp
              protocol: TCP
            - containerPort: 16270
              name: 16270tcp
              protocol: TCP
            - containerPort: 16271
              name: 16271tcp
              protocol: TCP
            - containerPort: 16272
              name: 16272tcp
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /server-data
              name: vol0
              subPath: ServerData
            - mountPath: /server-files
              name: vol0
              subPath: ServerFiles
        - name: pz-servernfs
          env:
            - name: NFS_EXPORT_0
              value: '/server-data *(rw,no_subtree_check)'
          image: erichough/nfs-server
          imagePullPolicy: Always
          ports:
            - containerPort: 2049
              name: 2049tcp
              protocol: TCP
            - containerPort: 111
              name: 111tcp
              protocol: TCP
            - containerPort: 32765
              name: 32765tcp
              protocol: TCP
            - containerPort: 32767
              name: 32767tcp
              protocol: TCP
            - containerPort: 2049
              name: 2049udp
              protocol: UDP
            - containerPort: 111
              name: 111udp
              protocol: UDP
            - containerPort: 32765
              name: 32765udp
              protocol: UDP
            - containerPort: 32767
              name: 32767udp
              protocol: UDP
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /server-data
              name: vol0
              subPath: ServerData
            - mountPath: /server-files
              name: vol0
              subPath: ServerFiles
      volumes:
        - name: vol0
          persistentVolumeClaim:
            claimName: zomboid # to be changed
