apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pz-server
    metallb.universe.tf/address-pool: fixed
  name: pz-tcp
  namespace: default
spec:
  ports:
#  - name: tcp27015
#    port: 27015
#    protocol: TCP
#    targetPort: 27015
  - name: tcp16262
    port: 16262
    protocol: TCP
    targetPort: 16262
  - name: tcp16263
    port: 16263
    protocol: TCP
    targetPort: 16263
  - name: tcp16264
    port: 16264
    protocol: TCP
    targetPort: 16264
  - name: tcp16265
    port: 16265
    protocol: TCP
    targetPort: 16265
  - name: tcp16266
    port: 16266
    protocol: TCP
    targetPort: 16266
  - name: tcp16267
    port: 16267
    protocol: TCP
    targetPort: 16267
  - name: tcp16268
    port: 16268
    protocol: TCP
    targetPort: 16268
  - name: tcp16269
    port: 16269
    protocol: TCP
    targetPort: 16269
  - name: tcp16270
    port: 16270
    protocol: TCP
    targetPort: 16270
  - name: tcp16271
    port: 16271
    protocol: TCP
    targetPort: 16271
  - name: tcp16272
    port: 16272
    protocol: TCP
    targetPort: 16272
  selector:
    app: pz-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.112
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pz-server
    metallb.universe.tf/address-pool: fixed
  name: pz-udp
  namespace: default
spec:
  ports:
  - name: udp8766
    port: 8766
    protocol: UDP
    targetPort: 8766
  - name: udp8767
    port: 8767
    protocol: UDP
    targetPort: 8767
  - name: udp16261
    port: 16261
    protocol: UDP
    targetPort: 16261
  selector:
    app: pz-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.112