apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 7dtd-server
    metallb.universe.tf/address-pool: fixed
  name: 7dtd-tcp
  namespace: default
spec:
  ports:
  - name: tcp26900
    port: 26900
    protocol: TCP
    targetPort: 26900
  selector:
    app: 7dtd-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.110
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 7dtd-server
    metallb.universe.tf/address-pool: fixed
  name: 7dtd-udp
  namespace: default
spec:
  ports:
  - name: udp26900
    port: 26900
    protocol: UDP
    targetPort: 26900
  - name: udp26901
    port: 26901
    protocol: UDP
    targetPort: 26901
  - name: udp26902
    port: 26902
    protocol: UDP
    targetPort: 26902
  selector:
    app: 7dtd-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.110