apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: server7dtd2
    metallb.universe.tf/address-pool: fixed
  name: tcpserver7dtd2
  namespace: default
spec:
  ports:
  - name: tcp26900
    port: 26900
    protocol: TCP
    targetPort: 26900
  selector:
    app: server7dtd2
  type: LoadBalancer
  loadBalancerIP: 192.168.30.110
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: server7dtd2
    metallb.universe.tf/address-pool: fixed
  name: udpserver7dtd2
  namespace: default
spec:
  ports:
  - name: udp26900
    port: 26900
    protocol: UDP
    targetPort: 26900
  - name: udp26901
    port: 26901
    protocol: UDP
    targetPort: 26901
  - name: udp26902
    port: 26902
    protocol: UDP
    targetPort: 26902
  selector:
    app: server7dtd2
  type: LoadBalancer
  loadBalancerIP: 192.168.30.110