apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: mc-server
    metallb.universe.tf/address-pool: fixed
  name: mc-tcp
  namespace: default
spec:
  ports:
  - name: tcp25565
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc-server
  type: LoadBalancer
  loadBalancerIP: 192.168.30.111
