apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minecraft-v1
    metallb.universe.tf/address-pool: fixed
  name: tcpminecraft
  namespace: default
spec:
  ports:
  - name: tcp25565
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft-v1
  type: LoadBalancer
  loadBalancerIP: 192.168.30.111
