apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - env: 
            - name: EULA
              value: "TRUE"
          image: itzg/minecraft-server
          imagePullPolicy: Always
          name: minecraft
          ports:
            - containerPort: 25565
              name: 25565tcp
              protocol: TCP
          resources:
          volumeMounts:
            - mountPath: /data
              name: vol0
              subPath: Data
      volumes:
        - name: vol0
          persistentVolumeClaim:
            claimName: minecraft