apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-v1
  name: minecraft-v1
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft-v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-v1
    spec:
      containers:
        - env: 
            - name: EULA
              value: "TRUE"
          image: itzg/minecraft-server
          imagePullPolicy: Always
          name: minecraft-v1
          ports:
            - containerPort: 25565
              name: 25565tcp
              protocol: TCP
          resources:
          volumeMounts:
            - mountPath: /data
              name: vol0
              subPath: Data
      volumes:
        - name: vol0
          nfs:
            path: /mnt/Alpha-Pool/K3s/Server_minecraft
            server: 192.168.10.206