apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-server
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
